### ISSUE TITLE
Adding gdal2tiles_parallel.py to makefile

### ISSUE THREAD

**Issue by DenisCarriere** [geo-data/gdal-docker#2]
Adding `gdal2tiles_parallel.py` will save lots of time generating the tiles across multiple cores.

At the moment the `gdal2tiles.py` only uses 1 core per process, it would be nice to run this process over 32 cores.

The guys at RGI are maintaining [Geopackage Python](https://github.com/GitHubRGI/geopackage-python) tools:

- [gdal2tiles_parallel.py](https://github.com/GitHubRGI/geopackage-python/blob/master/Tiling/gdal2tiles_parallel.py)
- [tiles2gpkg_parallel.py](https://github.com/GitHubRGI/geopackage-python/blob/master/Packaging/tiles2gpkg_parallel.py)

@homme Let me know if you have time to do it, or I can do a pull request, but I'm still new with Linux build. You seem to be the expert based on your Makefile! :)

**Comment by homme** [comment]
@DenisCarriere the tools look pretty useful, but I'd rather keep the docker image focused on GDAL itself: once you start supporting third party code which doesn't pin itself to specific GDAL versions there's always the risk that you'll have interoperability issues.  The best thing to do would be to create your own image based on the appropriately tagged `geodata/gdal` image.
