### ISSUE TITLE
Adding branch for GDAL 2.1

### ISSUE THREAD

**Issue by jehie** [geo-data/gdal-docker#3]
Hi,

Thanks for your great work! 

Would be great if we could have GDAL 2.1 also available, now as it is released officially few weeks ago. I could also create a branch with trunk replaced with 2.1.

Though I'm not sure how to push that stuff then to dockerhub.

Thanks!

**Comment by homme** [comment]
Hi, Thanks.  I've just added the [`2.1.0`](https://github.com/geo-data/gdal-docker/tree/2.1.0) branch and it's also available on the docker hub.
