### ISSUE TITLE
can't connect to gdal svn server

### ISSUE THREAD

**Issue by lhammond** [geo-data/gdal-docker#7]
Hi, tried building .. got the following

/usr/bin/svn checkout --quiet "http://svn.osgeo.org/gdal/trunk/" /tmp/gdal/ \
	&& touch -c /tmp/gdal
svn: E120108: Unable to connect to a repository at URL 'http://svn.osgeo.org/gdal/trunk'
svn: E120108: Error running context: The server unexpectedly closed the connection.
make: *** [/tmp/gdal] Error 1

![image](https://cloud.githubusercontent.com/assets/229602/23216485/1d21e4a8-f8e4-11e6-90ac-227100d0060f.png)

**Comment by homme** [comment]
I'm guessing this is probably a network issue or a temporary problem with the GDAL svn server: have you tried building again?
